import psycopg2

def migrate():
    conn = psycopg2.connect(
        dbname="stylear_db",
        user="postgres",
        password="123",
        host="localhost"
    )
    cursor = conn.cursor()

    try:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS imagen_producto (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                producto_id BIGINT NOT NULL,
                url TEXT NOT NULL,
                es_principal BOOLEAN NOT NULL DEFAULT FALSE,
                activo BOOLEAN NOT NULL DEFAULT TRUE,
                fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_imagen_producto
                    FOREIGN KEY (producto_id) REFERENCES producto (id)
                    ON UPDATE CASCADE ON DELETE CASCADE
            );
        """)
        conn.commit()
        print("Migration successful.")
    except Exception as e:
        conn.rollback()
        print(f"Error: {e}")
    finally:
        cursor.close()
        conn.close()

if __name__ == "__main__":
    migrate()
