-- =============================================================================
-- Migracion incremental Ciclo 2 - Bloque 1
-- Catalogo, detalle de prenda y disponibilidad por sucursal
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS inventario_sucursal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT NOT NULL,
    producto_variante_id BIGINT NOT NULL,
    stock_disponible INTEGER NOT NULL DEFAULT 0,
    stock_reservado INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT fk_inventario_sucursal_sucursal
        FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventario_sucursal_variante
        FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_inventario_sucursal_variante
        UNIQUE (sucursal_id, producto_variante_id),
    CONSTRAINT ck_inventario_stock_disponible
        CHECK (stock_disponible >= 0),
    CONSTRAINT ck_inventario_stock_reservado
        CHECK (stock_reservado >= 0),
    CONSTRAINT ck_inventario_stock_minimo
        CHECK (stock_minimo >= 0)
);

CREATE INDEX IF NOT EXISTS idx_inventario_sucursal_sucursal
    ON inventario_sucursal (sucursal_id);

CREATE INDEX IF NOT EXISTS idx_inventario_sucursal_variante
    ON inventario_sucursal (producto_variante_id);

-- Compatibilidad por si alguna base previa no tenia soporte completo de promociones.
CREATE TABLE IF NOT EXISTS promocion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT,
    tipo_descuento VARCHAR(30) NOT NULL,
    valor NUMERIC(12, 2) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_promocion_tipo
        CHECK (tipo_descuento IN ('PORCENTAJE', 'MONTO_FIJO')),
    CONSTRAINT ck_promocion_valor
        CHECK (
            (tipo_descuento = 'PORCENTAJE' AND valor > 0 AND valor <= 100)
            OR (tipo_descuento = 'MONTO_FIJO' AND valor >= 0)
        ),
    CONSTRAINT ck_promocion_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE IF NOT EXISTS promocion_producto (
    promocion_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    PRIMARY KEY (promocion_id, producto_id),
    CONSTRAINT fk_promocion_producto_promocion
        FOREIGN KEY (promocion_id) REFERENCES promocion (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_promocion_producto_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS promocion_sucursal (
    promocion_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL,
    PRIMARY KEY (promocion_id, sucursal_id),
    CONSTRAINT fk_promocion_sucursal_promocion
        FOREIGN KEY (promocion_id) REFERENCES promocion (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_promocion_sucursal_sucursal
        FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

COMMIT;
