BEGIN;

ALTER TABLE sucursal
    ADD COLUMN IF NOT EXISTS latitud NUMERIC(10, 7),
    ADD COLUMN IF NOT EXISTS longitud NUMERIC(10, 7);

UPDATE sucursal
SET latitud = COALESCE(latitud, -17.783327),
    longitud = COALESCE(longitud, -63.182140)
WHERE LOWER(COALESCE(nombre, '')) LIKE '%centro%';

UPDATE sucursal
SET latitud = COALESCE(latitud, -17.755129),
    longitud = COALESCE(longitud, -63.199901)
WHERE LOWER(COALESCE(nombre, '')) LIKE '%ventura%';

UPDATE sucursal
SET latitud = COALESCE(latitud, -17.783327),
    longitud = COALESCE(longitud, -63.182140)
WHERE latitud IS NULL OR longitud IS NULL;

ALTER TABLE venta
    ADD COLUMN IF NOT EXISTS tipo_entrega VARCHAR(30) NOT NULL DEFAULT 'RECOJO_SUCURSAL',
    ADD COLUMN IF NOT EXISTS costo_delivery NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE venta
    DROP CONSTRAINT IF EXISTS ck_venta_tipo_entrega;

ALTER TABLE venta
    ADD CONSTRAINT ck_venta_tipo_entrega
    CHECK (tipo_entrega IN ('RECOJO_SUCURSAL', 'DELIVERY'));

ALTER TABLE venta
    DROP CONSTRAINT IF EXISTS ck_venta_estado;

ALTER TABLE venta
    ADD CONSTRAINT ck_venta_estado
    CHECK (estado IN ('PENDIENTE_PAGO', 'COMPLETADA', 'ANULADA', 'RECHAZADA', 'CANCELADA'));

ALTER TABLE venta
    DROP CONSTRAINT IF EXISTS ck_venta_totales;

ALTER TABLE venta
    ADD CONSTRAINT ck_venta_totales
    CHECK (subtotal >= 0 AND descuento >= 0 AND total >= 0 AND costo_delivery >= 0);

CREATE TABLE IF NOT EXISTS delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL UNIQUE,
    sucursal_id BIGINT NOT NULL,
    cliente_id BIGINT,
    direccion_entrega TEXT NOT NULL,
    referencia TEXT,
    latitud_entrega NUMERIC(10, 7) NOT NULL,
    longitud_entrega NUMERIC(10, 7) NOT NULL,
    distancia_km NUMERIC(10, 2),
    tiempo_estimado_min INTEGER,
    costo_delivery NUMERIC(12, 2) NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_entrega TIMESTAMPTZ,
    observacion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_delivery_venta FOREIGN KEY (venta_id) REFERENCES venta (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_delivery_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_delivery_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_delivery_estado CHECK (
        estado IN ('PENDIENTE', 'EN_PREPARACION', 'EN_CAMINO', 'ENTREGADO', 'CANCELADO')
    ),
    CONSTRAINT ck_delivery_costo CHECK (costo_delivery >= 0)
);

CREATE INDEX IF NOT EXISTS idx_delivery_sucursal_id ON delivery (sucursal_id);
CREATE INDEX IF NOT EXISTS idx_delivery_cliente_id ON delivery (cliente_id);
CREATE INDEX IF NOT EXISTS idx_delivery_estado ON delivery (estado);
CREATE INDEX IF NOT EXISTS idx_delivery_fecha ON delivery (fecha_creacion);

INSERT INTO permiso (nombre, modulo, accion, descripcion, activo)
VALUES
    ('Solicitar delivery', 'VENTAS_INVENTARIO', 'delivery:solicitar', 'Permite solicitar delivery para una compra digital.', TRUE),
    ('Ver deliveries propios', 'VENTAS_INVENTARIO', 'delivery:ver_propios', 'Permite consultar deliveries propios del cliente.', TRUE),
    ('Ver deliveries de sucursal', 'VENTAS_INVENTARIO', 'delivery:ver_sucursal', 'Permite consultar deliveries de la sucursal asignada.', TRUE),
    ('Ver todos los deliveries', 'VENTAS_INVENTARIO', 'delivery:ver_todos', 'Permite consultar todos los deliveries del sistema.', TRUE),
    ('Gestionar estado de delivery', 'VENTAS_INVENTARIO', 'delivery:gestionar_estado', 'Permite actualizar el estado operativo de un delivery.', TRUE),
    ('Cancelar delivery', 'VENTAS_INVENTARIO', 'delivery:cancelar', 'Permite cancelar pedidos con delivery.', TRUE)
ON CONFLICT (modulo, accion) DO UPDATE
SET nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    activo = TRUE;

INSERT INTO rol_permiso (rol_id, permiso_id, activo)
SELECT r.id, p.id, TRUE
FROM rol r
JOIN permiso p ON p.modulo = 'VENTAS_INVENTARIO'
WHERE r.nombre = 'CLIENTE'
  AND p.accion IN ('delivery:solicitar', 'delivery:ver_propios')
ON CONFLICT (rol_id, permiso_id) DO UPDATE SET activo = TRUE;

INSERT INTO rol_permiso (rol_id, permiso_id, activo)
SELECT r.id, p.id, TRUE
FROM rol r
JOIN permiso p ON p.modulo = 'VENTAS_INVENTARIO'
WHERE r.nombre = 'ADMINISTRADOR'
  AND p.accion IN ('delivery:ver_todos', 'delivery:gestionar_estado', 'delivery:cancelar')
ON CONFLICT (rol_id, permiso_id) DO UPDATE SET activo = TRUE;

INSERT INTO rol_permiso (rol_id, permiso_id, activo)
SELECT r.id, p.id, TRUE
FROM rol r
JOIN permiso p ON p.modulo = 'VENTAS_INVENTARIO'
WHERE r.nombre = 'ENCARGADO_SUCURSAL'
  AND p.accion IN ('delivery:ver_sucursal', 'delivery:gestionar_estado', 'delivery:cancelar')
ON CONFLICT (rol_id, permiso_id) DO UPDATE SET activo = TRUE;

INSERT INTO rol_permiso (rol_id, permiso_id, activo)
SELECT r.id, p.id, TRUE
FROM rol r
JOIN permiso p ON p.modulo = 'VENTAS_INVENTARIO'
WHERE r.nombre = 'CAJERO'
  AND p.accion IN ('delivery:ver_sucursal', 'delivery:gestionar_estado')
ON CONFLICT (rol_id, permiso_id) DO UPDATE SET activo = TRUE;

COMMIT;
