-- =============================================================================
-- Script de Migración incremental: CU10 y CU11
-- Ejecuta este script en PostgreSQL si ya tienes una base de datos creada previamente.
-- =============================================================================

-- 1. Agregar columna categoria_padre_id a la tabla categoria (categorías recursivas)
ALTER TABLE categoria 
ADD COLUMN IF NOT EXISTS categoria_padre_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_name = 'categoria' AND constraint_name = 'fk_categoria_padre'
    ) THEN
        ALTER TABLE categoria
        ADD CONSTRAINT fk_categoria_padre
        FOREIGN KEY (categoria_padre_id) REFERENCES categoria (id)
        ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

-- 2. Crear tabla imagen_producto si no existe
CREATE TABLE IF NOT EXISTS imagen_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_imagen_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
