BEGIN;

CREATE TABLE IF NOT EXISTS registro_vestidor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES cliente(id) ON DELETE SET NULL,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    variante_id BIGINT REFERENCES producto_variante(id) ON DELETE SET NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    origen VARCHAR(50) NOT NULL DEFAULT 'MOVIL_AR'
);

CREATE INDEX IF NOT EXISTS idx_registro_vestidor_producto ON registro_vestidor(producto_id);
CREATE INDEX IF NOT EXISTS idx_registro_vestidor_cliente ON registro_vestidor(cliente_id);
CREATE INDEX IF NOT EXISTS idx_registro_vestidor_fecha ON registro_vestidor(fecha DESC);

COMMIT;
