BEGIN;

ALTER TABLE venta
    DROP CONSTRAINT IF EXISTS ck_venta_estado;

ALTER TABLE venta
    ADD CONSTRAINT ck_venta_estado
    CHECK (estado IN ('PENDIENTE_PAGO', 'COMPLETADA', 'ANULADA', 'RECHAZADA', 'CANCELADA'));

CREATE TABLE IF NOT EXISTS orden_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES venta(id) ON UPDATE CASCADE ON DELETE CASCADE,
    cliente_id BIGINT REFERENCES cliente(id) ON UPDATE CASCADE ON DELETE SET NULL,
    monto_total NUMERIC(12, 2) NOT NULL,
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    metodo VARCHAR(40) NOT NULL DEFAULT 'TARJETA',
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    proveedor VARCHAR(40) NOT NULL DEFAULT 'STRIPE',
    proveedor_session_id VARCHAR(255),
    proveedor_payment_intent_id VARCHAR(255),
    checkout_url TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_pago TIMESTAMPTZ,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_orden_pago_estado CHECK (estado IN ('PENDIENTE', 'PAGADO', 'RECHAZADO', 'EXPIRADO', 'CANCELADO')),
    CONSTRAINT ck_orden_pago_monto CHECK (monto_total >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_orden_pago_session
    ON orden_pago(proveedor_session_id)
    WHERE proveedor_session_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orden_pago_venta ON orden_pago(venta_id);
CREATE INDEX IF NOT EXISTS idx_orden_pago_cliente ON orden_pago(cliente_id);
CREATE INDEX IF NOT EXISTS idx_orden_pago_estado ON orden_pago(estado);

COMMIT;
