-- =============================================================================
-- Migracion incremental Ciclo 2 - Bloque 3
-- Inventario, movimientos, transferencias y ventas presenciales
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS movimiento_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT NOT NULL,
    producto_variante_id BIGINT NOT NULL,
    usuario_id BIGINT,
    tipo VARCHAR(40) NOT NULL,
    cantidad INTEGER NOT NULL,
    stock_anterior INTEGER NOT NULL,
    stock_nuevo INTEGER NOT NULL,
    motivo VARCHAR(255),
    referencia_tipo VARCHAR(60),
    referencia_id BIGINT,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_movimiento_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_variante FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_movimiento_tipo CHECK (
        tipo IN (
            'ENTRADA',
            'SALIDA',
            'AJUSTE_POSITIVO',
            'AJUSTE_NEGATIVO',
            'TRANSFERENCIA_ENTRADA',
            'TRANSFERENCIA_SALIDA',
            'VENTA_PRESENCIAL',
            'VENTA_DIGITAL'
        )
    ),
    CONSTRAINT ck_movimiento_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_movimiento_stock_no_negativo CHECK (stock_anterior >= 0 AND stock_nuevo >= 0)
);

CREATE INDEX IF NOT EXISTS idx_movimiento_sucursal ON movimiento_inventario (sucursal_id);
CREATE INDEX IF NOT EXISTS idx_movimiento_variante ON movimiento_inventario (producto_variante_id);
CREATE INDEX IF NOT EXISTS idx_movimiento_tipo ON movimiento_inventario (tipo);
CREATE INDEX IF NOT EXISTS idx_movimiento_fecha ON movimiento_inventario (fecha_movimiento);

CREATE TABLE IF NOT EXISTS transferencia_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_origen_id BIGINT NOT NULL,
    sucursal_destino_id BIGINT NOT NULL,
    usuario_id BIGINT,
    estado VARCHAR(30) NOT NULL DEFAULT 'COMPLETADA',
    observacion TEXT,
    fecha_transferencia TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_transferencia_origen FOREIGN KEY (sucursal_origen_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_transferencia_destino FOREIGN KEY (sucursal_destino_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_transferencia_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_transferencia_sucursales_distintas CHECK (sucursal_origen_id <> sucursal_destino_id),
    CONSTRAINT ck_transferencia_estado CHECK (estado IN ('PENDIENTE', 'COMPLETADA', 'CANCELADA'))
);

CREATE TABLE IF NOT EXISTS transferencia_stock_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferencia_id BIGINT NOT NULL,
    producto_variante_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    CONSTRAINT fk_transferencia_detalle_transferencia FOREIGN KEY (transferencia_id) REFERENCES transferencia_stock (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_transferencia_detalle_variante FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_transferencia_detalle_cantidad CHECK (cantidad > 0)
);

CREATE INDEX IF NOT EXISTS idx_transferencia_origen ON transferencia_stock (sucursal_origen_id);
CREATE INDEX IF NOT EXISTS idx_transferencia_destino ON transferencia_stock (sucursal_destino_id);

CREATE TABLE IF NOT EXISTS venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    sucursal_id BIGINT NOT NULL,
    usuario_id BIGINT,
    cliente_id BIGINT,
    tipo VARCHAR(30) NOT NULL DEFAULT 'PRESENCIAL',
    estado VARCHAR(30) NOT NULL DEFAULT 'COMPLETADA',
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    descuento NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    metodo_pago VARCHAR(40),
    observacion TEXT,
    fecha_venta TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_venta_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_venta_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_venta_tipo CHECK (tipo IN ('PRESENCIAL', 'WEB')),
    CONSTRAINT ck_venta_estado CHECK (estado IN ('COMPLETADA', 'ANULADA')),
    CONSTRAINT ck_venta_totales CHECK (subtotal >= 0 AND descuento >= 0 AND total >= 0)
);

CREATE TABLE IF NOT EXISTS venta_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL,
    producto_variante_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    descuento NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_venta_detalle_venta FOREIGN KEY (venta_id) REFERENCES venta (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_venta_detalle_variante FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_venta_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_venta_detalle_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX IF NOT EXISTS idx_venta_sucursal ON venta (sucursal_id);
CREATE INDEX IF NOT EXISTS idx_venta_fecha ON venta (fecha_venta);
CREATE INDEX IF NOT EXISTS idx_venta_usuario ON venta (usuario_id);
CREATE INDEX IF NOT EXISTS idx_venta_detalle_venta ON venta_detalle (venta_id);

COMMIT;
