-- =============================================================================
-- Migracion incremental Ciclo 2 - Bloque 2
-- Carrito de compras y reservas de prendas
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS carrito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT fk_carrito_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_carrito_cliente
    ON carrito (cliente_id);

CREATE TABLE IF NOT EXISTS carrito_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id BIGINT NOT NULL,
    producto_variante_id BIGINT NOT NULL,
    sucursal_id BIGINT,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(12, 2),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT fk_carrito_item_carrito
        FOREIGN KEY (carrito_id) REFERENCES carrito (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_carrito_item_variante
        FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_carrito_item_sucursal
        FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_carrito_item_cantidad CHECK (cantidad > 0)
);

CREATE INDEX IF NOT EXISTS idx_carrito_item_carrito
    ON carrito_item (carrito_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_carrito_item_variante_sucursal_activo
    ON carrito_item (carrito_id, producto_variante_id, COALESCE(sucursal_id, 0))
    WHERE activo = TRUE;

CREATE TABLE IF NOT EXISTS reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_reserva TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMPTZ,
    observacion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_sucursal
        FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_reserva_estado CHECK (
        estado IN ('PENDIENTE', 'PREPARADA', 'EN_ATENCION', 'COMPLETADA', 'CANCELADA', 'VENCIDA')
    ),
    CONSTRAINT ck_reserva_total CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_reserva_cliente
    ON reserva (cliente_id);

CREATE INDEX IF NOT EXISTS idx_reserva_sucursal
    ON reserva (sucursal_id);

CREATE INDEX IF NOT EXISTS idx_reserva_estado
    ON reserva (estado);

CREATE TABLE IF NOT EXISTS reserva_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT NOT NULL,
    producto_variante_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_reserva_detalle_reserva
        FOREIGN KEY (reserva_id) REFERENCES reserva (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_reserva_detalle_variante
        FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_reserva_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_reserva_detalle_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX IF NOT EXISTS idx_reserva_detalle_reserva
    ON reserva_detalle (reserva_id);

COMMIT;
