BEGIN;

CREATE TABLE IF NOT EXISTS devolucion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    venta_id BIGINT NOT NULL REFERENCES venta(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    cliente_id BIGINT REFERENCES cliente(id) ON UPDATE CASCADE ON DELETE SET NULL,
    sucursal_id BIGINT NOT NULL REFERENCES sucursal(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    solicitado_por_usuario_id BIGINT REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    revisado_por_usuario_id BIGINT REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    recibido_por_usuario_id BIGINT REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    estado VARCHAR(32) NOT NULL DEFAULT 'SOLICITADA',
    motivo TEXT NOT NULL,
    observacion TEXT,
    monto_solicitado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    monto_aprobado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    metodo_reembolso VARCHAR(24),
    proveedor_refund_id VARCHAR(255),
    proveedor_refund_estado VARCHAR(32),
    clave_idempotencia VARCHAR(100) NOT NULL UNIQUE,
    referencia_reembolso VARCHAR(255),
    error_reembolso TEXT,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_revision TIMESTAMPTZ,
    fecha_recepcion TIMESTAMPTZ,
    fecha_reembolso TIMESTAMPTZ,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_devolucion_estado CHECK (estado IN (
        'SOLICITADA', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'REEMBOLSO_PENDIENTE',
        'ERROR_REEMBOLSO', 'REEMBOLSADA', 'CANCELADA'
    )),
    CONSTRAINT ck_devolucion_montos CHECK (
        monto_solicitado >= 0 AND monto_aprobado >= 0 AND monto_aprobado <= monto_solicitado
    ),
    CONSTRAINT ck_devolucion_reembolso CHECK (
        metodo_reembolso IS NULL OR metodo_reembolso IN ('STRIPE', 'EFECTIVO', 'QR', 'OTRO')
    )
);

CREATE TABLE IF NOT EXISTS devolucion_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_id BIGINT NOT NULL REFERENCES devolucion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    venta_detalle_id BIGINT NOT NULL REFERENCES venta_detalle(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    cantidad_solicitada INTEGER NOT NULL,
    cantidad_aceptada INTEGER NOT NULL DEFAULT 0,
    cantidad_rechazada INTEGER NOT NULL DEFAULT 0,
    monto_aprobado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    observacion TEXT,
    inventario_repuesto BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_devolucion_detalle_linea UNIQUE (devolucion_id, venta_detalle_id),
    CONSTRAINT ck_devolucion_detalle_cantidades CHECK (
        cantidad_solicitada > 0 AND cantidad_aceptada >= 0 AND cantidad_rechazada >= 0
        AND cantidad_aceptada + cantidad_rechazada <= cantidad_solicitada
    ),
    CONSTRAINT ck_devolucion_detalle_monto CHECK (monto_aprobado >= 0)
);

ALTER TABLE devolucion
    ADD COLUMN IF NOT EXISTS cancelada_por_usuario_id BIGINT REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS reembolsada_por_usuario_id BIGINT REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS reembolso_iniciado_por_usuario_id BIGINT REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS fecha_reembolso_solicitud TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS fecha_cancelacion TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_devolucion_venta ON devolucion(venta_id, estado);
CREATE INDEX IF NOT EXISTS idx_devolucion_cliente_fecha ON devolucion(cliente_id, fecha_solicitud DESC);
CREATE INDEX IF NOT EXISTS idx_devolucion_sucursal_estado ON devolucion(sucursal_id, estado, fecha_solicitud DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_devolucion_refund_id
    ON devolucion(proveedor_refund_id) WHERE proveedor_refund_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_devolucion_detalle_linea ON devolucion_detalle(venta_detalle_id);

ALTER TABLE movimiento_inventario
    DROP CONSTRAINT IF EXISTS ck_movimiento_tipo;

ALTER TABLE movimiento_inventario
    ADD CONSTRAINT ck_movimiento_tipo CHECK (tipo IN (
        'ENTRADA', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO',
        'TRANSFERENCIA_ENTRADA', 'TRANSFERENCIA_SALIDA',
        'VENTA_PRESENCIAL', 'VENTA_DIGITAL', 'DEVOLUCION_VENTA'
    ));

INSERT INTO permiso (nombre, modulo, accion, descripcion, activo)
VALUES
    ('Solicitar devoluciones propias', 'VENTAS_INVENTARIO', 'devoluciones:solicitar', 'Permite solicitar la devolución de compras propias.', TRUE),
    ('Ver devoluciones propias', 'VENTAS_INVENTARIO', 'devoluciones:ver_propios', 'Permite consultar las devoluciones propias.', TRUE),
    ('Ver devoluciones de sucursal', 'VENTAS_INVENTARIO', 'devoluciones:ver_sucursal', 'Permite consultar devoluciones de la sucursal asignada.', TRUE),
    ('Ver todas las devoluciones', 'VENTAS_INVENTARIO', 'devoluciones:ver_todos', 'Permite consultar todas las devoluciones.', TRUE),
    ('Revisar devoluciones', 'VENTAS_INVENTARIO', 'devoluciones:revisar', 'Permite aprobar o rechazar devoluciones.', TRUE),
    ('Recibir productos devueltos', 'VENTAS_INVENTARIO', 'devoluciones:recibir', 'Permite registrar recepción e inspección de productos.', TRUE),
    ('Procesar reembolsos', 'VENTAS_INVENTARIO', 'devoluciones:reembolsar', 'Permite procesar o registrar reembolsos.', TRUE)
ON CONFLICT (modulo, accion) DO UPDATE SET nombre = EXCLUDED.nombre, descripcion = EXCLUDED.descripcion, activo = TRUE;

WITH asignaciones(rol_nombre, accion) AS (
    VALUES
        ('CLIENTE', 'devoluciones:solicitar'), ('CLIENTE', 'devoluciones:ver_propios'),
        ('ADMINISTRADOR', 'devoluciones:ver_todos'), ('ADMINISTRADOR', 'devoluciones:revisar'),
        ('ADMINISTRADOR', 'devoluciones:recibir'), ('ADMINISTRADOR', 'devoluciones:reembolsar'),
        ('ENCARGADO_SUCURSAL', 'devoluciones:ver_sucursal'), ('ENCARGADO_SUCURSAL', 'devoluciones:revisar'),
        ('ENCARGADO_SUCURSAL', 'devoluciones:recibir'), ('ENCARGADO_SUCURSAL', 'devoluciones:reembolsar'),
        ('CAJERO', 'devoluciones:ver_sucursal'), ('CAJERO', 'devoluciones:recibir')
)
INSERT INTO rol_permiso (rol_id, permiso_id, activo)
SELECT r.id, p.id, TRUE
FROM asignaciones a
JOIN rol r ON r.nombre = a.rol_nombre
JOIN permiso p ON p.modulo = 'VENTAS_INVENTARIO' AND p.accion = a.accion
ON CONFLICT (rol_id, permiso_id) DO UPDATE SET activo = TRUE;

DELETE FROM rol_permiso rp
USING rol r, permiso p
WHERE rp.rol_id = r.id AND rp.permiso_id = p.id
  AND r.nombre = 'CAJERO' AND p.modulo = 'VENTAS_INVENTARIO'
  AND p.accion = 'devoluciones:reembolsar';

COMMIT;
