BEGIN;

CREATE TABLE rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permiso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    modulo VARCHAR(80) NOT NULL,
    accion VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_permiso_modulo_accion UNIQUE (modulo, accion)
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    username VARCHAR(80) NOT NULL,
    correo VARCHAR(320) NOT NULL,
    password_hash TEXT NOT NULL,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    bloqueado_hasta TIMESTAMPTZ,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT ck_usuario_username CHECK (char_length(btrim(username)) >= 4),
    CONSTRAINT ck_usuario_correo CHECK (position('@' IN correo) > 1),
    CONSTRAINT ck_usuario_password_hash CHECK (char_length(password_hash) >= 20),
    CONSTRAINT ck_usuario_intentos_fallidos CHECK (intentos_fallidos >= 0)
);

CREATE UNIQUE INDEX uq_usuario_correo_lower
    ON usuario (lower(correo));

CREATE TABLE usuario_rol (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (rol_id) REFERENCES rol (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE rol_permiso (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (rol_id) REFERENCES rol (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (permiso_id) REFERENCES permiso (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE sesion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    refresh_token_hash TEXT,
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    fecha_cierre TIMESTAMPTZ,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    direccion_ip INET,
    user_agent TEXT,
    CONSTRAINT fk_sesion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_sesion_expiracion CHECK (fecha_expiracion > fecha_inicio)
);

CREATE INDEX idx_sesion_usuario
    ON sesion (usuario_id);

CREATE TABLE token_recuperacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    utilizado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_token_recuperacion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_token_recuperacion_expiracion CHECK (fecha_expiracion > fecha_creacion)
);

CREATE TABLE ciudad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    departamento VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ciudad_nombre_departamento UNIQUE (nombre, departamento)
);

CREATE TABLE sucursal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudad_id BIGINT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sucursal_ciudad
        FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_sucursal_ciudad_nombre UNIQUE (ciudad_id, nombre)
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    telefono VARCHAR(30),
    preferencias TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cliente_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE direccion_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    ciudad_id BIGINT NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    referencia VARCHAR(255),
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_direccion_cliente_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_direccion_cliente_ciudad
        FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE empleado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    sucursal_id BIGINT NOT NULL,
    codigo_empleado VARCHAR(40) NOT NULL UNIQUE,
    cargo VARCHAR(80) NOT NULL,
    fecha_ingreso DATE NOT NULL DEFAULT CURRENT_DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_empleado_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_empleado_sucursal
        FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    nit VARCHAR(40) UNIQUE,
    telefono VARCHAR(30),
    correo VARCHAR(320),
    direccion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_padre_id BIGINT,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categoria_padre
        FOREIGN KEY (categoria_padre_id) REFERENCES categoria (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE talla (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    descripcion VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE color (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    codigo_hex VARCHAR(7),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_color_codigo_hex
        CHECK (codigo_hex IS NULL OR codigo_hex ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE temporada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    anio SMALLINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_temporada_nombre_anio UNIQUE (nombre, anio),
    CONSTRAINT ck_temporada_anio CHECK (anio BETWEEN 2000 AND 2200)
);

CREATE TABLE coleccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temporada_id BIGINT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coleccion_temporada
        FOREIGN KEY (temporada_id) REFERENCES temporada (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_coleccion_temporada_nombre UNIQUE (temporada_id, nombre)
);

CREATE TABLE marca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL,
    marca_id BIGINT,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT,
    material VARCHAR(120),
    genero VARCHAR(40),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (categoria_id) REFERENCES categoria (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_producto_marca
        FOREIGN KEY (marca_id) REFERENCES marca (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX idx_producto_categoria
    ON producto (categoria_id);

CREATE INDEX idx_producto_marca
    ON producto (marca_id);

CREATE TABLE imagen_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_imagen_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE producto_variante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    talla_id BIGINT NOT NULL,
    color_id BIGINT NOT NULL,
    sku VARCHAR(80) NOT NULL UNIQUE,
    codigo_barras VARCHAR(80) UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_variante_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_variante_talla
        FOREIGN KEY (talla_id) REFERENCES talla (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_variante_color
        FOREIGN KEY (color_id) REFERENCES color (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_producto_variante UNIQUE (producto_id, talla_id, color_id)
);

CREATE TABLE producto_proveedor (
    producto_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    costo_referencia NUMERIC(12, 2),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (producto_id, proveedor_id),
    CONSTRAINT fk_producto_proveedor_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_producto_proveedor_proveedor
        FOREIGN KEY (proveedor_id) REFERENCES proveedor (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_producto_proveedor_costo CHECK (costo_referencia IS NULL OR costo_referencia >= 0)
);

CREATE TABLE producto_coleccion (
    producto_id BIGINT NOT NULL,
    coleccion_id BIGINT NOT NULL,
    PRIMARY KEY (producto_id, coleccion_id),
    CONSTRAINT fk_producto_coleccion_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_producto_coleccion_coleccion
        FOREIGN KEY (coleccion_id) REFERENCES coleccion (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE precio_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_variante_id BIGINT NOT NULL,
    precio NUMERIC(12, 2) NOT NULL,
    fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_precio_producto_variante
        FOREIGN KEY (producto_variante_id) REFERENCES producto_variante (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_precio_producto_precio CHECK (precio >= 0),
    CONSTRAINT ck_precio_producto_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE promocion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT,
    tipo_descuento VARCHAR(30) NOT NULL,
    valor NUMERIC(12, 2) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_promocion_tipo
        CHECK (tipo_descuento IN ('PORCENTAJE', 'MONTO_FIJO')),
    CONSTRAINT ck_promocion_valor
        CHECK (
            (tipo_descuento = 'PORCENTAJE' AND valor > 0 AND valor <= 100)
            OR (tipo_descuento = 'MONTO_FIJO' AND valor >= 0)
        ),
    CONSTRAINT ck_promocion_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE promocion_producto (
    promocion_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    PRIMARY KEY (promocion_id, producto_id),
    CONSTRAINT fk_promocion_producto_promocion
        FOREIGN KEY (promocion_id) REFERENCES promocion (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_promocion_producto_producto
        FOREIGN KEY (producto_id) REFERENCES producto (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE promocion_sucursal (
    promocion_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL,
    PRIMARY KEY (promocion_id, sucursal_id),
    CONSTRAINT fk_promocion_sucursal_promocion
        FOREIGN KEY (promocion_id) REFERENCES promocion (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_promocion_sucursal_sucursal
        FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE bitacora (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    accion VARCHAR(100) NOT NULL,
    modulo VARCHAR(100) NOT NULL,
    descripcion TEXT,
    resultado VARCHAR(20) NOT NULL DEFAULT 'EXITOSO',
    direccion_ip INET,
    user_agent TEXT,
    fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bitacora_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_bitacora_resultado CHECK (resultado IN ('EXITOSO', 'FALLIDO'))
);

COMMENT ON TABLE bitacora IS
'No guardar contrasenas, password_hash, access tokens, refresh tokens, claves secretas ni datos completos de tarjetas.';

CREATE INDEX idx_bitacora_fecha
    ON bitacora (fecha DESC);

CREATE INDEX idx_bitacora_usuario
    ON bitacora (usuario_id);

INSERT INTO rol (nombre, descripcion)
VALUES
    ('ADMINISTRADOR', 'Administrador general del sistema'),
    ('CLIENTE', 'Cliente de la tienda'),
    ('CAJERO', 'Empleado encargado de ventas y pagos en caja'),
    ('ENCARGADO_SUCURSAL', 'Empleado responsable de una sucursal'),
    ('PERSONAL_VENTAS', 'Empleado de atencion y ventas')
ON CONFLICT (nombre) DO NOTHING;

COMMIT;
